/*
 * SDRAM.c
 *
 *  Created on: 1 мая 2022 г.
 *      Author: hard_
 */
#include "SDRAM.h"


void init_SDRAM(){
	SDRAM_InitIO();
	SDRAM_InitFMC();

	uint16_t oldwert,istwert;
	  oldwert=SDRAM_Read16b(0x00);
	  SDRAM_Write16b(0x00, 0x5A3C);
	  istwert=SDRAM_Read16b(0x00);
	  SDRAM_Write16b(0x00, oldwert);
}

void SDRAM_InitIO(){
	//GPIOB init
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;

	GPIOB->MODER |= GPIO_MODER_MODER5_1;
	GPIOB->MODER |= GPIO_MODER_MODER6_1;

	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR5_1;
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR6_1;

	GPIOB->AFR[0] |= GPIO_AF_FMC<<(5*4);
	GPIOB->AFR[0] |= GPIO_AF_FMC<<(6*4);

	//GPIOC init
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;

	GPIOC->MODER |= GPIO_MODER_MODER0_1;

	GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR0_1;

	GPIOC->AFR[0] |= GPIO_AF_FMC;

	//GPIOD init
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;

	GPIOD->MODER |= GPIO_MODER_MODER0_1;
	GPIOD->MODER |= GPIO_MODER_MODER1_1;
	GPIOD->MODER |= GPIO_MODER_MODER8_1;
	GPIOD->MODER |= GPIO_MODER_MODER9_1;
	GPIOD->MODER |= GPIO_MODER_MODER10_1;
	GPIOD->MODER |= GPIO_MODER_MODER14_1;
	GPIOD->MODER |= GPIO_MODER_MODER15_1;

	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR0_1;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR1_1;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR8_1;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR9_1;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR10_1;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR14_1;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR15_1;

	GPIOD->AFR[0] |= GPIO_AF_FMC<<(0*4);
	GPIOD->AFR[0] |= GPIO_AF_FMC<<(1*4);
	GPIOD->AFR[1] |= GPIO_AF_FMC<<(0*4);
	GPIOD->AFR[1] |= GPIO_AF_FMC<<(1*4);
	GPIOD->AFR[1] |= GPIO_AF_FMC<<(2*4);
	GPIOD->AFR[1] |= GPIO_AF_FMC<<(6*4);
	GPIOD->AFR[1] |= GPIO_AF_FMC<<(7*4);

	//GPIOE init
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOEEN;

	GPIOE->MODER |= GPIO_MODER_MODER0_1;
	GPIOE->MODER |= GPIO_MODER_MODER1_1;
	GPIOE->MODER |= GPIO_MODER_MODER7_1;
	GPIOE->MODER |= GPIO_MODER_MODER8_1;
	GPIOE->MODER |= GPIO_MODER_MODER9_1;
	GPIOE->MODER |= GPIO_MODER_MODER10_1;
	GPIOE->MODER |= GPIO_MODER_MODER11_1;
	GPIOE->MODER |= GPIO_MODER_MODER12_1;
	GPIOE->MODER |= GPIO_MODER_MODER13_1;
	GPIOE->MODER |= GPIO_MODER_MODER14_1;
	GPIOE->MODER |= GPIO_MODER_MODER15_1;

	GPIOE->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR0_1;
	GPIOE->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR1_1;
	GPIOE->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR7_1;
	GPIOE->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR8_1;
	GPIOE->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR9_1;
	GPIOE->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR10_1;
	GPIOE->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR11_1;
	GPIOE->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR12_1;
	GPIOE->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR13_1;
	GPIOE->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR14_1;
	GPIOE->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR15_1;

	GPIOE->AFR[0] |= GPIO_AF_FMC<<(0*4);
	GPIOE->AFR[0] |= GPIO_AF_FMC<<(1*4);
	GPIOE->AFR[0] |= GPIO_AF_FMC<<(7*4);
	GPIOE->AFR[1] |= GPIO_AF_FMC<<(0*4);
	GPIOE->AFR[1] |= GPIO_AF_FMC<<(1*4);
	GPIOE->AFR[1] |= GPIO_AF_FMC<<(2*4);
	GPIOE->AFR[1] |= GPIO_AF_FMC<<(3*4);
	GPIOE->AFR[1] |= GPIO_AF_FMC<<(4*4);
	GPIOE->AFR[1] |= GPIO_AF_FMC<<(5*4);
	GPIOE->AFR[1] |= GPIO_AF_FMC<<(6*4);
	GPIOE->AFR[1] |= GPIO_AF_FMC<<(7*4);

	//GPIOF init
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOFEN;

	GPIOF->MODER |= GPIO_MODER_MODER0_1;
	GPIOF->MODER |= GPIO_MODER_MODER1_1;
	GPIOF->MODER |= GPIO_MODER_MODER2_1;
	GPIOF->MODER |= GPIO_MODER_MODER3_1;
	GPIOF->MODER |= GPIO_MODER_MODER4_1;
	GPIOF->MODER |= GPIO_MODER_MODER5_1;
	GPIOF->MODER |= GPIO_MODER_MODER11_1;
	GPIOF->MODER |= GPIO_MODER_MODER12_1;
	GPIOF->MODER |= GPIO_MODER_MODER13_1;
	GPIOF->MODER |= GPIO_MODER_MODER14_1;
	GPIOF->MODER |= GPIO_MODER_MODER15_1;

	GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR0_1;
	GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR1_1;
	GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR2_1;
	GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR3_1;
	GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR4_1;
	GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR5_1;
	GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR11_1;
	GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR12_1;
	GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR13_1;
	GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR14_1;
	GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR15_1;

	GPIOF->AFR[0] |= GPIO_AF_FMC<<(0*4);
	GPIOF->AFR[0] |= GPIO_AF_FMC<<(1*4);
	GPIOF->AFR[0] |= GPIO_AF_FMC<<(2*4);
	GPIOF->AFR[0] |= GPIO_AF_FMC<<(3*4);
	GPIOF->AFR[0] |= GPIO_AF_FMC<<(4*4);
	GPIOF->AFR[0] |= GPIO_AF_FMC<<(5*4);
	GPIOF->AFR[1] |= GPIO_AF_FMC<<(3*4);
	GPIOF->AFR[1] |= GPIO_AF_FMC<<(4*4);
	GPIOF->AFR[1] |= GPIO_AF_FMC<<(5*4);
	GPIOF->AFR[1] |= GPIO_AF_FMC<<(6*4);
	GPIOF->AFR[1] |= GPIO_AF_FMC<<(7*4);

	//GPIOG init
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOGEN;

	GPIOG->MODER |= GPIO_MODER_MODER0_1;
	GPIOG->MODER |= GPIO_MODER_MODER1_1;
	GPIOG->MODER |= GPIO_MODER_MODER4_1;
	GPIOG->MODER |= GPIO_MODER_MODER5_1;
	GPIOG->MODER |= GPIO_MODER_MODER8_1;
	GPIOG->MODER |= GPIO_MODER_MODER15_1;

	GPIOG->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR0_1;
	GPIOG->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR1_1;
	GPIOG->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR4_1;
	GPIOG->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR5_1;
	GPIOG->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR8_1;
	GPIOG->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR15_1;

	GPIOG->AFR[0] |= GPIO_AF_FMC<<(0*4);
	GPIOG->AFR[0] |= GPIO_AF_FMC<<(1*4);
	GPIOG->AFR[0] |= GPIO_AF_FMC<<(4*4);
	GPIOG->AFR[0] |= GPIO_AF_FMC<<(5*4);
	GPIOG->AFR[1] |= GPIO_AF_FMC<<(0*4);
	GPIOG->AFR[1] |= GPIO_AF_FMC<<(7*4);

}

//FMC_Bank2_SDRAM
void SDRAM_InitFMC(){
	RCC->AHB3ENR |= RCC_AHB3ENR_FMCEN;

	FMC_Bank5_6->SDCR[0] &= ~FMC_SDCR1_WP;
	FMC_Bank5_6->SDCR[0] &= ~FMC_SDCR1_CAS;
	FMC_Bank5_6->SDCR[0] &= ~FMC_SDCR1_NB;
	FMC_Bank5_6->SDCR[0] &= ~FMC_SDCR1_MWID;
	FMC_Bank5_6->SDCR[0] |= FMC_SDCR1_RPIPE_0;
	FMC_Bank5_6->SDCR[0] |= FMC_SDCR1_SDCLK_1;
	//FMC_Bank5_6->SDCR[0] &= ~FMC_SDCR1_RBURST;

	FMC_Bank5_6->SDCR[1] &= ~FMC_SDCR2_WP;
	FMC_Bank5_6->SDCR[1] |= FMC_SDCR2_NR_0;
	FMC_Bank5_6->SDCR[1] |= FMC_SDCR2_MWID_0;
	FMC_Bank5_6->SDCR[1] |= FMC_SDCR2_NB;
	FMC_Bank5_6->SDCR[1] |= FMC_SDCR2_CAS;
	FMC_Bank5_6->SDCR[1] |= FMC_SDCR2_SDCLK_1;
	FMC_Bank5_6->SDCR[1] |= FMC_SDCR2_RPIPE_0;

	FMC_Bank5_6->SDTR[0] &= ~0xFFFFFFFF;
    FMC_Bank5_6->SDTR[0] |= FMC_SDTR1_TRC_2 | FMC_SDTR1_TRC_1; //FMC_RowCycleDelay-1
    FMC_Bank5_6->SDTR[0] |= FMC_SDTR1_TRP_0;//FMC_RPDelay-1

    FMC_Bank5_6->SDTR[1] &= ~0xFFFFFFFF;
    FMC_Bank5_6->SDTR[1] |= FMC_SDTR1_TMRD_0; //FMC_LoadToActiveDelay-1
    FMC_Bank5_6->SDTR[1] |= FMC_SDTR1_TXSR_2 | FMC_SDTR2_TXSR_1; //FMC_ExitSelfRefreshDelay-1
    FMC_Bank5_6->SDTR[1] |= FMC_SDTR1_TRAS_1 | FMC_SDTR2_TRAS_0; //FMC_SelfRefreshTime-1
    FMC_Bank5_6->SDTR[1] |= FMC_SDTR1_TWR_0; //FMC_WriteRecoveryTime-1

    SDRAM_InitSeq();
    //P_SDRAM_InitSequence();
}

void SDRAM_InitSeq(){
	uint32_t tmpr = 0x0;

		while(FMC_Bank5_6->SDSR & FMC_SDSR_BUSY == FMC_SDSR_BUSY); //or !=
		/*
		FMC_Bank5_6->SDCMR &= 0;
		FMC_Bank5_6->SDCMR |= FMC_SDCMR_MODE_0;
		FMC_Bank5_6->SDCMR |= FMC_SDCMR_CTB2;
		*/
		  tmpr =   (uint32_t)(FMC_Command_Mode_CLK_Enabled |
				  	  	  	  FMC_Command_Target_bank2 |
		                     (((1)-1)<<5) |
		                     ((0)<<9));
		  FMC_Bank5_6->SDCMR = tmpr;
		for(int i = (100000 * 10); i != 0; i--);

		while(FMC_Bank5_6->SDSR & FMC_SDSR_BUSY == FMC_SDSR_BUSY); //or !=
		/*
		FMC_Bank5_6->SDCMR &= 0;
		FMC_Bank5_6->SDCMR |= FMC_SDCMR_MODE_1;
		FMC_Bank5_6->SDCMR |= FMC_SDCMR_CTB2;
		*/
		  tmpr =   (uint32_t)(FMC_Command_Mode_PALL |
				  	  	  	  FMC_Command_Target_bank2 |
		                     (((1)-1)<<5) |
		                     ((0)<<9));
		  FMC_Bank5_6->SDCMR = tmpr;
		while(FMC_Bank5_6->SDSR & FMC_SDSR_BUSY == FMC_SDSR_BUSY); //or !=
		/*
		FMC_Bank5_6->SDCMR &= 0;
		FMC_Bank5_6->SDCMR |= FMC_SDCMR_MODE_1 | FMC_SDCMR_MODE_0;
		FMC_Bank5_6->SDCMR |= FMC_SDCMR_CTB2;
		FMC_Bank5_6->SDCMR |= FMC_SDCMR_NRFS_1 | FMC_SDCMR_NRFS_0;
		*/
		  tmpr =   (uint32_t)(FMC_Command_Mode_AutoRefresh |
				  	  	  	  FMC_Command_Target_bank2 |
		                     (((4)-1)<<5) |
		                     ((0)<<9));
		  FMC_Bank5_6->SDCMR = tmpr;

		while(FMC_Bank5_6->SDSR & FMC_SDSR_BUSY == FMC_SDSR_BUSY); //or !=
		FMC_Bank5_6->SDCMR &= 0;
		//uint32_t tmpr = 0;
		/*
		tmpr = (uint32_t)0x0001           | //SDRAM_MODEREG_BURST_LENGTH_2
				  	  	   0x0000   		| //SDRAM_MODEREG_BURST_TYPE_SEQUENTIAL
						   0x0030           | //SDRAM_MODEREG_CAS_LATENCY_3
						   0x0000 			| //SDRAM_MODEREG_OPERATING_MODE_STANDARD
						   0x0200;			  //SDRAM_MODEREG_WRITEBURST_MODE_SINGLE
		FMC_Bank5_6->SDCMR |= FMC_SDCMR_MODE_2;
		FMC_Bank5_6->SDCMR |= FMC_SDCMR_CTB2;
		FMC_Bank5_6->SDCMR |= tmpr<<9;//<<9 = MRD
		*/
		uint32_t 	temp = (uint32_t)0x0001           | //SDRAM_MODEREG_BURST_LENGTH_2
		  	  	   0x0000   		| //SDRAM_MODEREG_BURST_TYPE_SEQUENTIAL
				   0x0030           | //SDRAM_MODEREG_CAS_LATENCY_3
				   0x0000 			| //SDRAM_MODEREG_OPERATING_MODE_STANDARD
				   0x0200;			  //SDRAM_MODEREG_WRITEBURST_MODE_SINGLE
		  tmpr =   (uint32_t)(FMC_Command_Mode_AutoRefresh |
				  	  	  	  FMC_Command_Target_bank2 |
		                     (((4)-1)<<5) |
		                     ((temp)<<9));
		  FMC_Bank5_6->SDCMR = tmpr;
		while(FMC_Bank5_6->SDSR & FMC_SDSR_BUSY == FMC_SDSR_BUSY); //or !=

		FMC_Bank5_6->SDRTR |= (683<<1); // Counter = (FMC_CLK * Refresh_Rate) - 20

		while(FMC_Bank5_6->SDSR & FMC_SDSR_BUSY == FMC_SDSR_BUSY); //or !=



}

void SDRAM_Write16b(uint32_t adr, uint16_t wert)
{
  *(uint16_t*) (SDRAM_START_ADR + adr) = wert;
}

uint16_t SDRAM_Read16b(uint32_t adr)
{
  uint16_t ret_wert=0;
  ret_wert = *(__IO uint16_t*)(SDRAM_START_ADR + adr);
  return(ret_wert);
}

